openapi: 3.0.0
info:
  version: 1.0.0
  title: realmeet
servers:
  - url: 'http://localhost:8080/v1'
paths:
  /rooms/{id}:
    get:
      summary: 'Return a room by id'
      operationId: getRoom
      tags:
        - room
      parameters:
        - name: id
          in: path
          description: ID of the room
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        404:
          description: Not found
    delete:
      summary: 'Delete a room by id'
      operationId: deleteRoom
      tags:
        - room
      parameters:
        - name: id
          in: path
          description: ID of the room
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 'Delete Successful'
        404:
          description: Not found
    put:
      summary: 'Update a room by id'
      operationId: updateRoom
      tags:
        - room
      parameters:
        - name: id
          in: path
          description: ID of the room
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoomDTO'
      responses:
        '204':
          description: 'Update Successful'
        404:
          description: Not found
        422:
          $ref: '#/components/responses/UnprocessableEntity'
  /rooms:
    post:
      summary: 'Create a room'
      operationId: createRoom
      tags:
        - room
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoomDTO'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
components:
  schemas:
    CreateRoomDTO:
      type: object
      properties:
        name:
          type: string
        seats:
          type: integer
    UpdateRoomDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateRoomDTO'
    RoomDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateRoomDTO'
        - type: object
          properties:
            id:
              type: integer
              format: int64
    ResponseError:
      type: object
      required:
        - field
        - errorCode
      properties:
        field:
          type: string
        errorCode:
          type: string
  responses:
    UnprocessableEntity:
      description: 'The server understands the content type of the request but was unable to process the contained instructions'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ResponseError'